openapi: 3.0.0
info:
  title: Constellation PacaSwap Metagraph
  description: "API for the PacaSwap Metagraph Layer 0 node handling swaps, liquidity pools, voting and governance"
  contact:
    email: developer@stardustcollective.org
  version: 0.0.1
tags:
  - name: Swap
    description: Manages swap operations and queries
  - name: LPs
    description: Manages liquidity pool operations
  - name: Vote
    description: Handles voting operations and weight calculations
  - name: Governance
    description: Manages reward allocations and governance
  - name: Staking
    description: Manages staking operations
  - name: Withdrawals
    description: Manages withdrawal operations and references
paths:
  /swap/quote:
    post:
      tags:
        - Swap
      summary: Get swap quote
      description: Get a quote for swapping one token for another, including rate, price impact, and estimated amounts
      requestBody:
        description: Swap quote parameters
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  $ref: './components.yml#/components/schemas/SwapQuoteRequest'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: './components.yml#/components/schemas/SwapQuote'
        400:
          description: Invalid request parameters
        404:
          description: Token pair not found
        500:
          description: Internal server error
  /swaps/{allowSpendHash}:
    get:
      tags:
        - Swap
      summary: Get swap details
      description: Retrieve swap information by allowSpendHash. Returns both pending and confirmed swaps.
      parameters:
        - name: allowSpendHash
          in: path
          required: true
          description: Hash of the allow spend transaction
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.yml#/components/schemas/Swap'
        404:
          description: Swap not found
  /liquidity-pools:
    get:
      tags:
        - LPs
      summary: List liquidity pools
      description: List all liquidity pools 
      parameters:
        - name: limit
          in: query
          description: Maximum number of items to return
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
        - name: offset
          in: query
          description: Number of items to skip
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                required: ["data", "meta"]
                properties:
                  data:
                    type: array
                    items:
                      $ref: './components.yml#/components/schemas/LiquidityPool'
                  meta:
                    $ref: './components.yml#/components/schemas/Pagination'
  /liquidity-pools/{poolId}:
    get:
      tags:
        - LPs
      summary: Show liquidity pool
      description: Show liquidity pool by pool ID
      parameters:
        - name: poolId
          in: path
          required: true
          description: Unique identifier of the liquidity pool
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                required: ["data"]
                properties:
                  data:
                    $ref: './components.yml#/components/schemas/LiquidityPool'
        404:
          description: Liquidity pool not found
  /liquidity-pools/{poolId}/shares/{address}:
    get:
      tags:
        - LPs
      summary: Get liquidity pool shares
      description: Get the amount of shares an address holds in a specific liquidity pool
      parameters:
        - name: poolId
          in: path
          required: true
          description: Unique identifier of the liquidity pool
          schema:
            type: string
            minLength: 1
        - name: address
          in: path
          required: true
          description: Address to query shares for
          schema:
            type: string
            minLength: 1
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                required: ["data"]
                properties:
                  data:
                    type: object
                    required: ["poolId", "address", "shares"]
                    properties:
                      poolId:
                        type: string
                        description: Unique identifier of the liquidity pool
                      address:
                        type: string
                        description: Address that owns the shares
                      shares:
                        type: integer
                        description: Amount of shares owned by the address
                        minimum: 0
        404:
          description: Liquidity pool not found
  /addresses/{address}/vote-info:
    get:
      tags:
        - Vote
      summary: Get address voting info
      description: Retrieve voting information for a specific address including credits and allocations
      parameters:
        - name: address
          in: path
          required: true
          description: Address to query
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.yml#/components/schemas/VoteInfo'
        404:
          description: Address not found
  /addresses/{address}/vote-info/last-reference:
    get:
      tags:
        - Vote
      summary: Get last vote reference
      description: Retrieve the last reference for vote information of a specific address
      parameters:
        - name: address
          in: path
          required: true
          description: Address to query
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.yml#/components/schemas/LastReference'
  /addresses/{address}/vote-weight:
    get:
      tags:
        - Vote
      summary: Get voting weight
      description: Retrieve the vote weight for a specific address based on token locks
      parameters:
        - name: address
          in: path
          required: true
          description: Address to query
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.yml#/components/schemas/VotingWeight'
        404:
          description: Address not found
  /addresses/{address}/withdrawals/last-reference:
    get:
      tags:
        - Withdrawals
      summary: Get last withdrawal reference
      description: Retrieve the last withdrawal reference for a specific address
      parameters:
        - name: address
          in: path
          required: true
          description: Address to query
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.yml#/components/schemas/WithdrawalReference'
  /governance/allocations/rewards:
    get:
      tags:
        - Governance
      summary: Get allocation rewards
      description: Retrieve current governance allocation rewards
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.yml#/components/schemas/GovAllocationRewards'
  /addresses/{address}/stakings/last-reference:
    get:
      tags:
        - Staking
      summary: Get last staking reference
      description: Retrieve the last staking reference for a specific address
      parameters:
        - name: address
          in: path
          required: true
          description: Address to query
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.yml#/components/schemas/LastReference'
