openapi: 3.0.0
info:
  title: Constellation PacaSwap Metagraph
  description: "API for the PacaSwap Metagraph Layer 0 node handling swaps, liquidity pools, voting and governance"
  contact:
    email: developer@stardustcollective.org
  version: 0.0.1
tags:
  - name: Swap
    description: Manages swap operations and queries
  - name: LPs
    description: Manages liquidity pool operations
  - name: Vote
    description: Handles voting operations and weight calculations
  - name: Governance Rounds
    description: Information about governance voting
  - name: Staking
    description: Manages staking operations
  - name: Withdrawals
    description: Manages withdrawal operations and references
  - name: Reward Withdrawals
    description: Manages reward withdrawals
  - name: Health Check
    description: Get information about the healthiness of the node
  - name: Config
    description: Get information about the metagraph config
paths:
  /swap/quote:
    post:
      tags:
        - Swap
      summary: Get swap quote
      description: Get a quote for swapping one token for another, including rate, price impact, and estimated amounts
      requestBody:
        description: Swap quote parameters
        required: true
        content:
          application/json:
            schema:
              $ref: './components.yml#/components/schemas/SwapQuoteRequest'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: './components.yml#/components/schemas/SwapQuote'
        400:
          description: Invalid request parameters
        404:
          description: Token pair not found
        500:
          description: Internal server error
  /swap/quote/reverse:
    post:
      tags:
        - Swap
      summary: Get the reverse swap quote
      description: Get a quote for swapping one token for another, including rate, price impact, and estimated amounts. This endpoint requires the desired output and then we calculate the required input
      requestBody:
        description: Swap quote parameters
        required: true
        content:
          application/json:
            schema:
              $ref: './components.yml#/components/schemas/SwapQuoteRequest'
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: './components.yml#/components/schemas/SwapQuoteReverse'
        400:
          description: Invalid request parameters
        404:
          description: Token pair not found
        500:
          description: Internal server error
  /swaps/{swapHash}/state:
    get:
      tags:
        - Swap
      summary: Get swap details
      description: Retrieve swap information by swap hash.
      parameters:
        - name: swapHash
          in: path
          required: true
          description: Hash of the swap data update
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.yml#/components/schemas/SwapStateResponse'
        404:
          description: Swap not found
  /addresses/{address}/swaps/last-reference:
    get:
      tags:
        - Swap
      summary: Get last swap reference
      description: Retrieve the last swap reference for a specific address
      parameters:
        - name: address
          in: path
          required: true
          description: Address to query
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.yml#/components/schemas/LastReference'
  /liquidity-pools:
    get:
      tags:
        - LPs
      summary: List liquidity pools
      description: List all liquidity pools 
      parameters:
        - name: limit
          in: query
          description: Maximum number of items to return
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
        - name: offset
          in: query
          description: Number of items to skip
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: address
          in: query
          description: Address with pool shares
          example: 'DAGaa99YgUGKQef92D34FGRBGnAiKUBoEmjNoIrL'
          schema:
            type: string
        - name: tokenId
          in: query
          description: Pools with tokenId
          schema:
            type: string
          examples:
            DAG:
              summary: Native DAG token
              value: "DAG"
            DAGAddress:
              summary: Token represented by a DAG address
              value: "DAGaa99YgUGKQef92D34FGRBGnAiKUBoEmjNoIrL"
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                required: ["data", "meta"]
                properties:
                  data:
                    type: array
                    items:
                      $ref: './components.yml#/components/schemas/LiquidityPool'
                  meta:
                    $ref: './components.yml#/components/schemas/Pagination'
  /liquidity-pools/{poolId}:
    get:
      tags:
        - LPs
      summary: Show liquidity pool
      description: Show liquidity pool by pool ID
      parameters:
        - name: poolId
          in: path
          required: true
          description: Unique identifier of the liquidity pool
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                required: ["data"]
                properties:
                  data:
                    $ref: './components.yml#/components/schemas/LiquidityPool'
        404:
          description: Liquidity pool not found
  /liquidity-pools/{poolId}/shares/{address}:
    get:
      tags:
        - LPs
      summary: Get liquidity pool shares
      description: Get the amount of shares an address holds in a specific liquidity pool
      parameters:
        - name: poolId
          in: path
          required: true
          description: Unique identifier of the liquidity pool
          schema:
            type: string
            minLength: 1
        - name: address
          in: path
          required: true
          description: Address to query shares for
          schema:
            type: string
            minLength: 1
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                required: ["data"]
                properties:
                  data:
                    type: object
                    required: ["poolId", "address", "shares"]
                    properties:
                      poolId:
                        type: string
                        description: Unique identifier of the liquidity pool
                      address:
                        type: string
                        description: Address that owns the shares
                      shares:
                        type: integer
                        description: Amount of shares owned by the address
                        minimum: 0
        404:
          description: Liquidity pool not found
  /liquidity-pools/{lpHash}/state:
    get:
      tags:
        - LPs
      summary: Get liquidity pool update details
      description: Retrieve liquidity pool update information by lp hash.
      parameters:
        - name: lpHash
          in: path
          required: true
          description: Hash of the lp data update
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.yml#/components/schemas/LiquidityPoolStateResponse'
        404:
          description: LP not found
  /addresses/{address}/vote-info:
    get:
      tags:
        - Vote
      summary: Get address voting info
      description: Retrieve voting information for a specific address including credits and allocations
      parameters:
        - name: address
          in: path
          required: true
          description: Address to query
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.yml#/components/schemas/VoteInfo'
        404:
          description: Address not found
  /addresses/{address}/vote-info/last-reference:
    get:
      tags:
        - Vote
      summary: Get last vote reference
      description: Retrieve the last reference for vote information of a specific address
      parameters:
        - name: address
          in: path
          required: true
          description: Address to query
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.yml#/components/schemas/LastReference'
  /addresses/{address}/vote-weight:
    get:
      tags:
        - Vote
      summary: Get voting weight
      description: Retrieve the vote weight for a specific address based on token locks
      parameters:
        - name: address
          in: path
          required: true
          description: Address to query
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.yml#/components/schemas/VotingPower'
        404:
          description: Address not found
  /addresses/{address}/withdrawals/last-reference:
    get:
      tags:
        - Withdrawals
      summary: Get last withdrawal reference
      description: Retrieve the last withdrawal reference for a specific address
      parameters:
        - name: address
          in: path
          required: true
          description: Address to query
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.yml#/components/schemas/WithdrawalReference'

  /withdrawals/{withdrawalHash}/state:
    get:
      tags:
        - Withdrawals
      summary: Get withdrawal update details
      description: Retrieve withdrawal update information by withdrawal hash.
      parameters:
        - name: withdrawalHash
          in: path
          required: true
          description: Hash of the withdrawal data update
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.yml#/components/schemas/WithdrawalStateResponse'
        404:
          description: Withdrawal not found

  /governance-rounds/last/voting-result:
    get:
      tags:
        - Governance Rounds
      summary: Get allocation result for previous month
      description: Retrieve current governance allocation
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.yml#/components/schemas/FrozenAddressesVotes'

  /governance-rounds/last/distributed-rewards:
    get:
      tags:
        - Governance Rounds
      summary: Total distributed reward for previous month
      description: Retrieve previous month reward distribution per type
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.yml#/components/schemas/DistributionReward'

  /governance-rounds/current/distributed-rewards:
    get:
      tags:
        - Governance Rounds
      summary: Total distributed reward for current month
      description: Retrieve current reward distribution per type
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.yml#/components/schemas/DistributionReward'

  /governance-rounds/current/allocations:
    get:
      tags:
        - Governance Rounds
      summary: Current allocation (vote) process status
      description: Retrieve current allocation data
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: './components.yml#/components/schemas/CurrentAllocationsForAddress'

  /governance-rounds/current/month-reference:
    get:
      tags:
        - Governance Rounds
      summary: Current month-reference process status
      description: Retrieve current month-reference data
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './components.yml#/components/schemas/CurrentMonthReference'
  /governance-rounds/stats:
    get:
      tags:
        - Governance Rounds
      summary: Governance stats
      description: Governance stats
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: './components.yml#/components/schemas/AllocationStats'

  /addresses/{address}/stakings/last-reference:
    get:
      tags:
        - Staking
      summary: Get last staking reference
      description: Retrieve the last staking reference for a specific address
      parameters:
        - name: address
          in: path
          required: true
          description: Address to query
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.yml#/components/schemas/LastReference'
  /stakings/{stakingHash}/state:
    get:
      tags:
        - Staking
      summary: Get staking update details
      description: Retrieve staking update information by staking hash.
      parameters:
        - name: stakingHash
          in: path
          required: true
          description: Hash of the staking data update
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.yml#/components/schemas/StakingStateResponse'
        404:
          description: Staking not found

  /health-check/last-global-snapshot-sync:
    get:
      tags:
        - Health Check
      summary: Get last global snapshot sync by node
      description: Get last global snapshot sync by node
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: './components.yml#/components/schemas/LastSyncGlobalSnapshot'
        500:
          description: Internal server error
  /addresses/{address}/rewards/withdrawals/last-reference:
    get:
      tags:
        - Reward Withdrawals
      summary: Get last reward withdrawal reference
      description: Retrieve the last reward withdrawal reference for a specific address
      parameters:
        - name: address
          in: path
          required: true
          description: Address to query
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.yml#/components/schemas/LastReference'
  /addresses/{address}/rewards/balance:
    get:
      tags:
        - Reward Withdrawals
      summary: Get wallet reward available balances
      description: Get wallet reward available balances
      parameters:
        - name: address
          in: path
          required: true
          description: Address to query
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: './components.yml#/components/schemas/RewardsWithdrawalAvailableBalances'
  /config:
    get:
      tags:
        - Config
      summary: Get the metagraph config
      description: Get the metagraph config
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: './components.yml#/components/schemas/Config'
        500:
          description: Internal server error