name: Global L0 Genesis
description: "Starts the Global L0 Genesis node"

inputs:
  CL_PUBLIC_HTTP_PORT:
    description: "Public HTTP port for the node"
    required: true
  CL_P2P_HTTP_PORT:
    description: "P2P HTTP port for the node"
    required: true
  CL_CLI_HTTP_PORT:
    description: "CLI HTTP port for the node"
    required: true

runs:
  using: "composite"
  steps:
    - name: Running dag-l0
      shell: bash
      env:
        CL_KEYSTORE: token-key.p12
        CL_KEYALIAS: token-key
        CL_PASSWORD: password
        CL_PUBLIC_HTTP_PORT: ${{ inputs.CL_PUBLIC_HTTP_PORT }}
        CL_P2P_HTTP_PORT: ${{ inputs.CL_P2P_HTTP_PORT }}
        CL_CLI_HTTP_PORT: ${{ inputs.CL_CLI_HTTP_PORT }}
        CL_APP_ENV: dev
        CL_COLLATERAL: 0
      run: |
        cd ${{ github.workspace }}/.github/code/hypergraph/dag-l0/genesis-node
        java -jar ${{ github.workspace }}/.github/code/shared_jars/cl-keytool.jar generate

        touch dag-l0-genesis.log
        nohup java -Denvironment=dev -jar ${{ github.workspace }}/.github/code/hypergraph/dag-l0.jar run-genesis genesis.csv --ip 127.0.0.1 > dag-l0-genesis.log 2>&1 &
        sleep 5

    - name: Check if node started
      shell: bash
      env:
        CL_PUBLIC_HTTP_PORT: ${{ inputs.CL_PUBLIC_HTTP_PORT }}
      run: |
        npx tsx ${{ github.workspace }}/.github/action_scripts/check_if_node_started.ts -url=http://127.0.0.1:${CL_PUBLIC_HTTP_PORT}/node/info -cluster_name=DAG-L0