name: Liquidity Pool Tests
on:
  workflow_call:
    inputs:
      amm_metagraph_hash:
        required: true
        type: string
        description: "Hash for the amm-metagraph artifact"
      currency_metagraph_1_hash:
        required: true
        type: string
        description: "Hash for the currency-metagraph-1 artifact"
      currency_metagraph_2_hash:
        required: true
        type: string
        description: "Hash for the currency-metagraph-2 artifact"
      hypergraph_hash:
        required: true
        type: string
        description: "Hash for the hypergraph artifact"
      shared_jars_hash:
        required: true
        type: string
        description: "Hash for the shared_jars artifact"
jobs:
  liquidity-pool-tests:
    runs-on: Ubuntu-22-64-core
    steps:
      - uses: actions/checkout@v4

      - name: Debug - Echo workspace path
        run: |
          echo "github.workspace: ${{ github.workspace }}"
          echo "PWD: $(pwd)"
          ls -la

      - name: Debug - Echo hash inputs
        run: |
          echo "amm_metagraph_hash: ${{ inputs.amm_metagraph_hash }}"
          echo "currency_metagraph_1_hash: ${{ inputs.currency_metagraph_1_hash }}"
          echo "currency_metagraph_2_hash: ${{ inputs.currency_metagraph_2_hash }}"
          echo "hypergraph_hash: ${{ inputs.hypergraph_hash }}"
          echo "shared_jars_hash: ${{ inputs.shared_jars_hash }}"

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: .github/action_scripts/package-lock.json

      - name: Installing node dependencies
        shell: bash
        run: |
          cd .github/action_scripts
          npm i @stardust-collective/dag4
          npm i js-sha256
          npm i axios
          npm i brotli
          npm i zod

      - name: Download shared_jars artifacts
        uses: actions/download-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: shared_jars-${{ runner.os }}-${{ inputs.shared_jars_hash }}
          path: .github/code/shared_jars

      - name: Download Hypergraph Artifact
        uses: actions/download-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: hypergraph-${{ runner.os }}-${{ inputs.hypergraph_hash }}
          path: .github/code/hypergraph

      - name: Download AMM Metagraph Artifact
        uses: actions/download-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: amm-metagraph-${{ runner.os }}-${{ inputs.amm_metagraph_hash }}
          path: .github/code/metagraphs/amm

      - name: Download Currency Metagraph 1 Artifact
        uses: actions/download-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: currency-metagraph-1-${{ runner.os }}-${{ inputs.currency_metagraph_1_hash }}
          path: .github/code/metagraphs/currency-1

      - name: Download Currency Metagraph 2 Artifact
        uses: actions/download-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: currency-metagraph-2-${{ runner.os }}-${{ inputs.currency_metagraph_2_hash }}
          path: .github/code/metagraphs/currency-2

      - name: Start Hypergraph
        uses: "./.github/templates/actions/hypergraph/start"
        with:
          INCLUDE_DAG_L1: true
          DAG_L0_PORT_PREFIX: 90
          DAG_L1_PORT_PREFIX: 91

      - name: Start Metagraph - AMM
        uses: "./.github/templates/actions/metagraph/start"
        with:
          INCLUDE_DATA_L1: true
          METAGRAPH_NAME: amm-metagraph
          DL0_PORT_PREFIX: 90
          ML0_PORT_PREFIX: 80
          CL1_PORT_PREFIX: 81
          DL1_PORT_PREFIX: 82

      - name: Start Token A Currency
        uses: "./.github/templates/actions/metagraph/start"
        with:
          INCLUDE_DATA_L1: false
          METAGRAPH_NAME: currency-metagraph-1
          DL0_PORT_PREFIX: 90
          ML0_PORT_PREFIX: 70
          CL1_PORT_PREFIX: 71

      - name: Start Token B Currency
        uses: "./.github/templates/actions/metagraph/start"
        with:
          INCLUDE_DATA_L1: false
          METAGRAPH_NAME: currency-metagraph-2
          DL0_PORT_PREFIX: 90
          ML0_PORT_PREFIX: 60
          CL1_PORT_PREFIX: 61

      - name: Check if node is ready to receive token locks
        uses: "./.github/templates/actions/metagraph/check_l1_ready_to_consensus"
        with:
          METAGRAPH_NAME: amm-metagraph
          INTERVAL: 5
          MAX_RETRIES: 60
          PHRASE: "No enough last N global snapshots present"

      - name: Start liquidity pool tests
        shell: bash
        env:
          GL0_URL: ${{ secrets.GL0_URL || 'http://localhost:9000' }}
          DAG_CL1_URL: ${{ secrets.DAG_CL1_URL || 'http://localhost:9100' }}
          AMM_ML0_URL: ${{ secrets.AMM_ML0_URL || 'http://localhost:8000' }}
          AMM_CL1_URL: ${{ secrets.AMM_CL1_URL || 'http://localhost:8100' }}
          AMM_DL1_URL: ${{ secrets.AMM_DL1_URL || 'http://localhost:8200' }}
          TOKEN_A_CL1_URL: ${{ secrets.CURRENCY_1_CL1_URL || 'http://localhost:7100' }}
          TOKEN_A_ML0_URL: ${{ secrets.CURRENCY_1_ML0_URL || 'http://localhost:7000' }}
          TOKEN_B_CL1_URL: ${{ secrets.CURRENCY_2_CL1_URL || 'http://localhost:6100' }}
          TOKEN_B_ML0_URL: ${{ secrets.CURRENCY_2_ML0_URL || 'http://localhost:6000' }}
        run: |
          AMM_METAGRAPH_ID=$(cat .github/code/metagraphs/amm-metagraph/metagraph-l0/genesis-node/genesis.address)
          echo "AMM_METAGRAPH_ID: $AMM_METAGRAPH_ID"
          TOKEN_A_ID=$(cat .github/code/metagraphs/currency-metagraph-1/metagraph-l0/genesis-node/genesis.address)
          echo "TOKEN_A_ID: $TOKEN_A_ID"
          TOKEN_B_ID=$(cat .github/code/metagraphs/currency-metagraph-2/metagraph-l0/genesis-node/genesis.address)
          echo "TOKEN_B_ID: $TOKEN_B_ID"
          cd .github/action_scripts
          npx tsx amm-operations/main.ts \
            $GL0_URL \
            $DAG_CL1_URL \
            $AMM_ML0_URL \
            $AMM_CL1_URL \
            $AMM_DL1_URL \
            $TOKEN_A_CL1_URL \
            $TOKEN_B_CL1_URL \
            $TOKEN_A_ML0_URL \
            $TOKEN_B_ML0_URL \
            $AMM_METAGRAPH_ID \
            $TOKEN_A_ID \
            $TOKEN_B_ID

      - name: Upload log files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: node-log-files-${{ runner.os }}-${{ hashFiles(format('{0}/**/build.sbt', github.workspace), format('{0}/**/src/main/scala/org/amm_metagraph/**', github.workspace)) }}
          path: .github/code/**/*.log
          if-no-files-found: warn
          retention-days: 7
