name: Governance tests

on:
  workflow_call:

jobs:
  governance-tests:
    runs-on: Ubuntu-22-64-core
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: .github/action_scripts/package-lock.json

      - name: Installing node dependencies
        shell: bash
        run: |
          cd .github/action_scripts
          npm i @stardust-collective/dag4
          npm i js-sha256
          npm i axios
          npm i brotli
          npm i zod

      - name: Download shared_jars artifacts
        uses: actions/download-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: shared_jars-${{ runner.os }}-${{ hashFiles(format('{0}/**/build.sbt', github.workspace), format('{0}/**/src/main/scala/org/amm_metagraph/**', github.workspace)) }}
          path: .github/code/shared_jars

      - name: Download Hypergraph Artifact
        uses: actions/download-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: hypergraph-${{ runner.os }}-${{ hashFiles(format('{0}/**/build.sbt', github.workspace), format('{0}/**/src/main/scala/org/amm_metagraph/**', github.workspace)) }}
          path: .github/code/hypergraph

      - name: Download AMM Metagraph Artifact
        uses: actions/download-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: amm-metagraph-${{ runner.os }}-${{ hashFiles(format('{0}/**/build.sbt', github.workspace), format('{0}/**/src/main/scala/org/amm_metagraph/**', github.workspace)) }}
          path: .github/code/metagraphs/amm-metagraph

      - name: Start Hypergraph
        uses: "./.github/templates/actions/hypergraph/start"
        with:
          INCLUDE_DAG_L1: true
          DAG_L0_PORT_PREFIX: 90
          DAG_L1_PORT_PREFIX: 91

      - name: Start Metagraph - AMM
        uses: "./.github/templates/actions/metagraph/start"
        with:
          INCLUDE_DATA_L1: true
          METAGRAPH_NAME: amm-metagraph
          DL0_PORT_PREFIX: 90
          ML0_PORT_PREFIX: 80
          CL1_PORT_PREFIX: 81
          DL1_PORT_PREFIX: 82

      - name: Check if node is ready to receive token locks
        uses: "./.github/templates/actions/metagraph/check_l1_ready_to_consensus"
        with:
          METAGRAPH_NAME: amm-metagraph
          INTERVAL: 5
          MAX_RETRIES: 60
          PHRASE: "No enough last N global snapshots present"

      - name: Start governance tests
        shell: bash
        env:
          GL0_URL: ${{ secrets.GL0_URL }}
          AMM_ML0_URL: ${{ secrets.AMM_ML0_URL }}
          AMM_CL1_URL: ${{ secrets.AMM_CL1_URL }}
          AMM_DL1_URL: ${{ secrets.AMM_DL1_URL }}
          TOKEN_LOCKS: ${{ secrets.TOKEN_LOCKS }}
        run: |
          METAGRAPH_ID=$(cat .github/code/metagraphs/amm-metagraph/metagraph-l0/genesis-node/genesis.address)
          echo "METAGRAPH_ID: $METAGRAPH_ID"

          cd .github/action_scripts
          npx tsx governance/main.ts \
            $GL0_URL \
            $AMM_ML0_URL \
            $AMM_CL1_URL \
            $AMM_DL1_URL \
            $METAGRAPH_ID
