name: Liquidity Pool Tests

on:
  workflow_call:

jobs:
  liquidity-pool-tests:
    runs-on: Ubuntu-22-64-core
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: .github/action_scripts/package-lock.json

      - name: Installing node dependencies
        shell: bash
        run: |
          cd .github/action_scripts
          npm i @stardust-collective/dag4
          npm i js-sha256
          npm i axios
          npm i brotli
          npm i zod
          npm i tsx

      - name: Download shared_jars artifacts
        uses: actions/download-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: shared_jars
          path: .github/code/shared_jars

      - name: Download Hypergraph Artifact
        uses: actions/download-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: hypergraph
          path: .github/code/hypergraph

      - name: Download AMM Metagraph Artifact
        uses: actions/download-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: amm-metagraph
          path: .github/code/metagraphs/amm-metagraph

      - name: Start Hypergraph
        uses: "./.github/templates/actions/hypergraph/start"
        with:
          INCLUDE_DAG_L1: true
          DAG_L0_PORT_PREFIX: 90
          DAG_L1_PORT_PREFIX: 91

      - name: Start Metagraph - AMM
        uses: "./.github/templates/actions/metagraph/start"
        with:
          INCLUDE_DATA_L1: true
          METAGRAPH_NAME: amm-metagraph
          DL0_PORT_PREFIX: 90
          ML0_PORT_PREFIX: 80
          CL1_PORT_PREFIX: 81
          DL1_PORT_PREFIX: 82

      - name: Start Token A Currency
        uses: "./.github/templates/actions/metagraph/start"
        with:
          INCLUDE_DATA_L1: false
          METAGRAPH_NAME: currency-metagraph-1
          DL0_PORT_PREFIX: 90
          ML0_PORT_PREFIX: 70
          CL1_PORT_PREFIX: 71

      - name: Start Token B Currency
        uses: "./.github/templates/actions/metagraph/start"
        with:
          INCLUDE_DATA_L1: false
          METAGRAPH_NAME: currency-metagraph-1
          DL0_PORT_PREFIX: 90
          ML0_PORT_PREFIX: 60
          CL1_PORT_PREFIX: 61

      - name: Start liquidity pool tests
        shell: bash
        env:
          # TODO: Can be constructed from PROT_PREFIX
          GL0_URL: ${{ secrets.GL0_URL || 'http://localhost:9000' }}
          AMM_ML0_URL: ${{ secrets.AMM_ML0_URL || 'http://localhost:8000' }}
          AMM_CL1_URL: ${{ secrets.AMM_CL1_URL || 'http://localhost:8100' }}
          AMM_DL1_URL: ${{ secrets.AMM_DL1_URL || 'http://localhost:8200' }}
          TOKEN_A_CL1_URL: ${{ secrets.CURRENCY_1_CL1_URL || 'http://localhost:7100' }}
          TOKEN_A_ML0_URL: ${{ secrets.CURRENCY_1_ML0_URL || 'http://localhost:7000' }}
          TOKEN_B_CL1_URL: ${{ secrets.CURRENCY_2_CL1_URL || 'http://localhost:6100' }}
          TOKEN_B_ML0_URL: ${{ secrets.CURRENCY_2_ML0_URL || 'http://localhost:6000' }}
        run: |
          AMM_METAGRAPH_ID=$(cat .github/code/metagraphs/amm-metagraph/metagraph-l0/genesis-node/genesis.address)
          echo "AMM_METAGRAPH_ID: $AMM_METAGRAPH_ID"

          TOKEN_A_ID=$(cat .github/code/metagraphs/currency-metagraph-1/metagraph-l0/genesis-node/genesis.address)
          echo "TOKEN_A_ID: $TOKEN_A_ID"

          TOKEN_B_ID=$(cat .github/code/metagraphs/currency-metagraph-2/metagraph-l0/genesis-node/genesis.address)
          echo "TOKEN_B_ID: $TOKEN_B_ID"

          cd .github/action_scripts
          tsx lp/lp_creation_test.ts \
            $GL0_URL \
            $AMM_ML0_URL \
            $AMM_CL1_URL \
            $AMM_DL1_URL \
            $TOKEN_A_CL1_URL \
            $TOKEN_B_CL1_URL \
            $AMM_METAGRAPH_ID \
            $TOKEN_A_ID \
            $TOKEN_B_ID
