name: main

on:
  pull_request: {}

jobs:
  call-workflow-setup-environment:
    uses: ./.github/workflows/setup-environment.yml
    with:
      tessellation_commit_hash: "98d79c0eeaec9de9492c19bedb63d50343f1516e"
      use_merge_commit: true
    secrets: inherit

  debug-outputs:
    runs-on: ubuntu-latest
    needs: call-workflow-setup-environment
    steps:
      - name: Debug outputs
        run: |
          echo "call-workflow-setup-environment outputs: ${{ toJSON(needs.call-workflow-setup-environment.outputs) }}"

  call-governance-tests:
    needs: [call-workflow-setup-environment]
    uses: ./.github/workflows/governance_tests.yml
    with:
      tessellation_version: ${{ needs.call-workflow-setup-environment.outputs.tessellation_version }}
      amm_metagraph_hash: ${{ needs.call-workflow-setup-environment.outputs.amm_metagraph_hash }}
    secrets: inherit

  call-amm-operations-tests:
    needs: [call-workflow-setup-environment]
    uses: ./.github/workflows/amm_operations_test.yml
    with:
      tessellation_version: ${{ needs.call-workflow-setup-environment.outputs.tessellation_version }}
      amm_metagraph_hash: ${{ needs.call-workflow-setup-environment.outputs.amm_metagraph_hash }}
      currency_metagraph_1_hash: ${{ needs.call-workflow-setup-environment.outputs.currency_metagraph_1_hash }}
      currency_metagraph_2_hash: ${{ needs.call-workflow-setup-environment.outputs.currency_metagraph_2_hash }}
    secrets: inherit
