name: Start environment

on:
  workflow_call:

jobs:
  start-environment:
    runs-on: Ubuntu-22-64-core
    steps:
      - uses: actions/checkout@v4
        with:
          ref: adding-testing-templates

      - uses: actions/setup-node@v4
        with:
          node-version: 16.14.2
          cache: 'npm'
          cache-dependency-path: .github/action_scripts/package-lock.json

      - name: Installing node-fetch@2.6.6
        shell: bash
        run: |
          cd .github/action_scripts
          npm i node-fetch@2.6.6

      - name: Download shared_jars artifacts
        uses: actions/download-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: shared_jars
          path: .github/code/shared_jars

      - name: Download Hypergraph Artifact
        uses: actions/download-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: hypergraph
          path: .github/code/hypergraph

      - name: Download AMM Metagraph Artifact
        uses: actions/download-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: amm-metagraph
          path: .github/code/metagraphs/amm-metagraph

      - name: Download Currency Metagraph 1 Artifact
        uses: actions/download-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: currency-metagraph-1
          path: .github/code/metagraphs/currency-metagraph-1

      - name: Download Currency Metagraph 2 Artifact
        uses: actions/download-artifact@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: currency-metagraph-2
          path: .github/code/metagraphs/currency-metagraph-2

      - name: Start Hypergraph
        uses: "./.github/templates/actions/hypergraph/start"
        with:
          INCLUDE_DAG_L1: true
          DAG_L0_PORT_PREFIX: 90
          DAG_L1_PORT_PREFIX: 91

      - name: Start Metagraph - AMM
        uses: "./.github/templates/actions/metagraph/start"
        with:
          INCLUDE_DATA_L1: true
          METAGRAPH_NAME: amm-metagraph
          DL0_PORT_PREFIX: 90
          ML0_PORT_PREFIX: 80
          CL1_PORT_PREFIX: 81
          DL1_PORT_PREFIX: 82

      - name: Start Metagraph - Currency Metagraph 1
        uses: "./.github/templates/actions/metagraph/start"
        with:
          INCLUDE_DATA_L1: false
          METAGRAPH_NAME: currency-metagraph-1
          DL0_PORT_PREFIX: 90
          ML0_PORT_PREFIX: 70
          CL1_PORT_PREFIX: 71

      - name: Start Metagraph - Currency Metagraph 2
        uses: "./.github/templates/actions/metagraph/start"
        with:
          INCLUDE_DATA_L1: false
          METAGRAPH_NAME: currency-metagraph-2
          DL0_PORT_PREFIX: 90
          ML0_PORT_PREFIX: 60
          CL1_PORT_PREFIX: 61